#lanuage
language: python
#version
python:
  - "3.7"

#env:
  #- NOSE_REDNOSE=1
  
# command to install dependencies
install:
  - pip install -r requirements.txt

services:
  - sqlite
  
# command to run tests
script:
  - python manage.py test
